# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================

"""Functional correctness assertions for the bio_lab performance e2e test."""

import json
import re
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Any

from loguru import logger
from performance_config import _ORIGINAL_SQLITE_PATH
from performance_query_cases import (
    EXPECTED_ANTIBODY_COUNT,
    EXPECTED_ANTIBODY_IDS,
    EXPECTED_BD55_1111_ANTIBODY_SAMPLE_ID,
    EXPECTED_BD368_NEUTRALIZED_PSEUDOVIRUSES,
    EXPECTED_CELL_COUNT,
    EXPECTED_CELL_IDS,
    EXPECTED_HUH7_CELL_SAMPLE_ID,
    EXPECTED_NEW_EXPERIMENT_STATUS,
    EXPECTED_PSEUDOVIRUS_COUNT,
    EXPECTED_PSEUDOVIRUS_IDS,
    EXPECTED_XBB15_PSEUDOVIRUS_SAMPLE_ID,
    TC_EXPECTED_ANSWER_ASSERTIONS,
    TC_EXPECTED_SQL_ASSERTIONS,
    TC_NON_BLOCKING_REVIEW_CASES,
)


def _find_created_experiment_id(db_path: Path, today: str) -> int | None:
    """Query the bio_lab.sqlite DB for the experiment created by Q1.

    A "valid Q1 creation" is a row in ``neutralization_experiments`` joined
    with ``experiments`` that satisfies ALL of:
      - inhibitor_sample_id  = EXPECTED_BD55_1111_ANTIBODY_SAMPLE_ID
      - pseudovirus_sample_id = EXPECTED_XBB15_PSEUDOVIRUS_SAMPLE_ID
      - cell_sample_id       = EXPECTED_HUH7_CELL_SAMPLE_ID
      - experiments.status   = EXPECTED_NEW_EXPERIMENT_STATUS
      - experiments.start_date = today (the test run date)

    Returns the experiment id (int) if found, else None. The id is
    auto-generated by the agent's INSERT script (e.g. 902036 in the deepseek
    reference run) so it cannot be predicted ahead of time.
    """

    if not db_path.exists():
        return None
    conn = sqlite3.connect(str(db_path))
    try:
        cur = conn.execute(
            """
            SELECT ne.id
            FROM neutralization_experiments ne
            JOIN experiments e ON ne.id = e.id
            WHERE ne.inhibitor_sample_id = ?
              AND ne.pseudovirus_sample_id = ?
              AND ne.cell_sample_id = ?
              AND e.status = ?
              AND e.start_date = ?
            ORDER BY ne.id DESC
            LIMIT 1
            """,
            (
                EXPECTED_BD55_1111_ANTIBODY_SAMPLE_ID,
                EXPECTED_XBB15_PSEUDOVIRUS_SAMPLE_ID,
                EXPECTED_HUH7_CELL_SAMPLE_ID,
                EXPECTED_NEW_EXPERIMENT_STATUS,
                today,
            ),
        )
        row = cur.fetchone()
        return int(row[0]) if row and row[0] is not None else None
    finally:
        conn.close()


find_created_experiment_id = _find_created_experiment_id


def _strip_sql_fences(sql_text: str) -> str:
    sql_text = re.sub(r"^\s*```(?:sql)?\s*", "", sql_text, flags=re.IGNORECASE)
    sql_text = re.sub(r"\s*```\s*$", "", sql_text)
    return sql_text.strip()


def _strip_leading_sql_comments(statement: str) -> str:
    text = statement.strip()
    while True:
        new_text = re.sub(r"^\s*--[^\n]*(?:\n|$)", "", text)
        new_text = re.sub(r"^\s*/\*.*?\*/", "", new_text, flags=re.DOTALL).strip()
        if new_text == text:
            return text
        text = new_text


def _split_sql_statements(sql_text: str) -> list[str]:
    statements: list[str] = []
    current: list[str] = []
    in_single = False
    in_double = False
    in_line_comment = False
    in_block_comment = False
    i = 0
    while i < len(sql_text):
        char = sql_text[i]
        next_char = sql_text[i + 1] if i + 1 < len(sql_text) else ""

        if in_line_comment:
            current.append(char)
            if char == "\n":
                in_line_comment = False
            i += 1
            continue
        if in_block_comment:
            current.append(char)
            if char == "*" and next_char == "/":
                current.append(next_char)
                in_block_comment = False
                i += 2
            else:
                i += 1
            continue
        if in_single:
            current.append(char)
            if char == "'" and next_char == "'":
                current.append(next_char)
                i += 2
                continue
            if char == "'":
                in_single = False
            i += 1
            continue
        if in_double:
            current.append(char)
            if char == '"' and next_char == '"':
                current.append(next_char)
                i += 2
                continue
            if char == '"':
                in_double = False
            i += 1
            continue

        if char == "-" and next_char == "-":
            current.extend([char, next_char])
            in_line_comment = True
            i += 2
            continue
        if char == "/" and next_char == "*":
            current.extend([char, next_char])
            in_block_comment = True
            i += 2
            continue
        if char == "'":
            current.append(char)
            in_single = True
            i += 1
            continue
        if char == '"':
            current.append(char)
            in_double = True
            i += 1
            continue
        if char == ";":
            statement = "".join(current).strip()
            if statement:
                statements.append(statement)
            current = []
            i += 1
            continue

        current.append(char)
        i += 1

    statement = "".join(current).strip()
    if statement:
        statements.append(statement)
    return statements


def _normalize_sql_value(value: Any) -> str:
    if value is None:
        return "<NULL>"
    if isinstance(value, float):
        return f"{value:.12g}"
    return str(value)


def _canonicalize_rows(rows: list[tuple[Any, ...]]) -> list[tuple[str, ...]]:
    return sorted(tuple(_normalize_sql_value(value) for value in row) for row in rows)


def _execute_sql_result_sets(
    db_path: Path, sql_text: str, source: str
) -> tuple[list[dict[str, Any]], list[dict[str, str]]]:
    result_sets: list[dict[str, Any]] = []
    errors: list[dict[str, str]] = []
    cleaned_sql = _strip_sql_fences(sql_text)
    statements = _split_sql_statements(cleaned_sql)
    conn = sqlite3.connect(f"file:{db_path.resolve().as_posix()}?mode=ro", uri=True)
    try:
        for idx, statement in enumerate(statements, 1):
            executable = _strip_leading_sql_comments(statement)
            if not executable:
                continue
            first_token = executable.split(None, 1)[0].lower()
            if first_token not in {"select", "with", "pragma"}:
                continue
            try:
                cur = conn.execute(statement)
                columns = [col[0] for col in cur.description or []]
                rows = cur.fetchall() if cur.description else []
            except Exception as exc:
                errors.append(
                    {
                        "source": source,
                        "statement_index": str(idx),
                        "error": str(exc),
                        "sql": statement,
                    }
                )
                continue
            result_sets.append(
                {
                    "source": source,
                    "statement_index": idx,
                    "sql": statement,
                    "columns": columns,
                    "row_count": len(rows),
                    "canonical_rows": _canonicalize_rows(rows),
                    "preview_rows": [list(row) for row in rows[:10]],
                }
            )
    finally:
        conn.close()
    return result_sets, errors


def _combined_generated_result_sets(result_sets: list[dict[str, Any]]) -> list[dict[str, Any]]:
    by_width: dict[int, list[dict[str, Any]]] = {}
    for result in result_sets:
        if result["row_count"] == 0:
            continue
        width = len(result["canonical_rows"][0]) if result["canonical_rows"] else len(result["columns"])
        by_width.setdefault(width, []).append(result)

    combined: list[dict[str, Any]] = []
    for width, same_width_results in by_width.items():
        if len(same_width_results) < 2:
            continue
        rows: list[tuple[str, ...]] = []
        sources: list[str] = []
        for result in same_width_results:
            rows.extend(result["canonical_rows"])
            sources.append(f"{result['source']}#{result['statement_index']}")
        combined.append(
            {
                "source": "combined_generated_result_sets",
                "statement_index": 0,
                "sql": "\n".join(sources),
                "columns": [f"column_{i + 1}" for i in range(width)],
                "row_count": len(rows),
                "canonical_rows": sorted(rows),
                "preview_rows": [list(row) for row in sorted(rows)[:10]],
            }
        )
    return combined


def _matches_unqueryable_answer(response: dict[str, Any], rule: dict[str, list[str]]) -> bool:
    """Accept a schema-boundary answer only when it names the unavailable fields."""
    answer = str(response.get("final_answer", ""))
    sql_files = [
        Path(path)
        for path in response.get("sql_files", [])
        if ".context" not in Path(path).parts and ".memory" not in Path(path).parts
    ]
    required_terms = rule.get("required_terms", [])
    unavailable_terms = rule.get("unavailable_terms", [])
    return (
        not sql_files
        and all(term in answer for term in required_terms)
        and any(term in answer for term in unavailable_terms)
    )


def _schema_fields_are_absent(db_path: Path, rule: dict[str, Any]) -> bool:
    forbidden_terms = [str(term).casefold() for term in rule.get("forbidden_schema_terms", [])]
    conn = sqlite3.connect(f"file:{db_path.resolve().as_posix()}?mode=ro", uri=True)
    try:
        columns: list[str] = []
        for table in rule.get("schema_tables", []):
            columns.extend(str(row[1]).casefold() for row in conn.execute(f"PRAGMA table_info({table})"))
    finally:
        conn.close()
    return not any(term in column for term in forbidden_terms for column in columns)


def _answer_reports_absence(response: dict[str, Any], rule: dict[str, Any]) -> bool:
    answer = str(response.get("final_answer", "")).casefold()
    required_answer_terms = [str(term).casefold() for term in rule.get("required_answer_terms", [])]
    absence_answer_terms = [str(term).casefold() for term in rule.get("absence_answer_terms", [])]
    return all(term in answer for term in required_answer_terms) and any(
        term in answer for term in absence_answer_terms
    )


def _matches_absence_assertion(
    response: dict[str, Any],
    generated_result_sets: list[dict[str, Any]],
    rule: dict[str, Any],
) -> bool:
    """Require an absence conclusion supported by relevant empty or NULL SQL output."""
    has_absence_answer = not rule.get("require_absence_answer", True) or _answer_reports_absence(response, rule)
    sql_term_groups = rule.get("sql_term_groups", [])
    null_column = rule.get("generated_null_column")
    expected_row_count = rule.get("expected_generated_row_count")
    allow_empty_result = rule.get("allow_empty_generated_result", True)

    for term_group in sql_term_groups:
        has_group_absence_evidence = False
        for result in generated_result_sets:
            sql_text = result["sql"].casefold()
            has_relevant_sql = any(str(term).casefold() in sql_text for term in term_group)
            has_empty_result = allow_empty_result and result["row_count"] == 0
            has_expected_row_count = expected_row_count is None or result["row_count"] == expected_row_count
            has_null_result = (
                isinstance(null_column, int)
                and result["row_count"] > 0
                and has_expected_row_count
                and all(len(row) > null_column and row[null_column] == "<NULL>" for row in result["canonical_rows"])
            )
            if has_relevant_sql and (has_empty_result or has_null_result):
                has_group_absence_evidence = True
                break

        if not has_group_absence_evidence:
            return False

    return has_absence_answer and bool(sql_term_groups)


def _matches_sql_evidence(
    generated_result_sets: list[dict[str, Any]],
    rule: dict[str, Any],
) -> dict[str, Any] | None:
    """Match result-backed evidence without constraining the generated SQL shape."""
    required_sql_terms = [str(term).casefold() for term in rule.get("required_sql_terms", [])]
    null_column = rule.get("null_column")
    allow_empty_result = rule.get("allow_empty_result", True)

    for result in generated_result_sets:
        sql_text = result["sql"].casefold()
        if not all(term in sql_text for term in required_sql_terms):
            continue

        has_empty_result = allow_empty_result and result["row_count"] == 0
        has_null_result = (
            isinstance(null_column, int)
            and result["row_count"] > 0
            and all(len(row) > null_column and row[null_column] == "<NULL>" for row in result["canonical_rows"])
        )
        if has_empty_result or has_null_result:
            return {
                "source": result["source"],
                "statement_index": result["statement_index"],
                "row_count": result["row_count"],
                "preview_rows": result["preview_rows"],
                "sql": result["sql"],
            }

    return None


def _match_result_payload(
    expected: dict[str, Any],
    generated: dict[str, Any],
    match_mode: str,
    core_rows: list[tuple[str, ...]] | None = None,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "match_mode": match_mode,
        "expected": {
            "source": expected["source"],
            "row_count": expected["row_count"],
            "preview_rows": expected["preview_rows"],
        },
        "generated": {
            "source": generated["source"],
            "statement_index": generated["statement_index"],
            "row_count": generated["row_count"],
            "preview_rows": generated["preview_rows"],
        },
    }
    if core_rows is not None:
        payload["core_row_count"] = len(core_rows)
        payload["core_preview_rows"] = [list(row) for row in core_rows[:10]]
    return payload


def _project_result_rows(
    result: dict[str, Any],
    column_indexes: list[int],
) -> list[tuple[str, ...]] | None:
    if not column_indexes:
        return None
    rows = result["canonical_rows"]
    if any(any(index >= len(row) for index in column_indexes) for row in rows):
        return None
    if not rows and any(index >= len(result["columns"]) for index in column_indexes):
        return None
    return sorted(tuple(row[index] for index in column_indexes) for row in rows)


def _extract_json_field_rows(
    result: dict[str, Any],
    id_column: int,
    value_column: int,
    json_key: str | None = None,
) -> list[tuple[str, str]] | None:
    rows = result["canonical_rows"]
    if any(max(id_column, value_column) >= len(row) for row in rows):
        return None
    if not rows and max(id_column, value_column) >= len(result["columns"]):
        return None

    extracted_rows: list[tuple[str, str]] = []
    for row in rows:
        value = row[value_column]
        if json_key is not None:
            if value == "<NULL>":
                extracted_value = "<NULL>"
            else:
                try:
                    parsed_value = json.loads(value)
                except json.JSONDecodeError:
                    return None
                if not isinstance(parsed_value, dict):
                    return None
                extracted_value = _normalize_sql_value(parsed_value.get(json_key))
        else:
            extracted_value = value
        extracted_rows.append((row[id_column], extracted_value))
    return sorted(extracted_rows)


def _match_tc_result_sets(
    expected_result_sets: list[dict[str, Any]],
    generated_result_sets: list[dict[str, Any]],
    assertion_spec: dict[str, Any],
) -> dict[str, Any] | None:
    if assertion_spec.get("semantic_mismatch_reason"):
        return None

    core_columns = assertion_spec.get("core_result_columns")
    if core_columns:
        for expected in expected_result_sets:
            expected_core_rows = _project_result_rows(expected, core_columns["expected"])
            if expected_core_rows is None:
                continue
            for generated in generated_result_sets:
                generated_core_rows = _project_result_rows(generated, core_columns["generated"])
                if generated_core_rows == expected_core_rows:
                    return _match_result_payload(
                        expected,
                        generated,
                        "core_result_columns",
                        expected_core_rows,
                    )

        return None

    core_json_field = assertion_spec.get("core_json_field")
    if core_json_field:
        for expected in expected_result_sets:
            expected_core_rows = _extract_json_field_rows(
                expected,
                core_json_field["expected_id_column"],
                core_json_field["expected_json_column"],
                json_key=core_json_field["json_key"],
            )
            if expected_core_rows is None:
                continue
            for generated in generated_result_sets:
                generated_core_rows = _extract_json_field_rows(
                    generated,
                    core_json_field["generated_id_column"],
                    core_json_field["generated_value_column"],
                )
                if generated_core_rows == expected_core_rows:
                    return _match_result_payload(
                        expected,
                        generated,
                        "core_json_field",
                        expected_core_rows,
                    )

        return None

    for expected in expected_result_sets:
        for generated in generated_result_sets:
            if generated["canonical_rows"] == expected["canonical_rows"]:
                return _match_result_payload(expected, generated, "exact_result_set")

    return None


def _record_non_blocking_tc_reviews(
    response_by_key: dict[str, dict[str, Any]],
    tc_results: dict[str, dict[str, Any]],
) -> None:
    """Record TC semantics that still need a human decision without failing the run."""
    for query_key, review_spec in TC_NON_BLOCKING_REVIEW_CASES.items():
        response = response_by_key.get(query_key)
        if response is None:
            continue

        reason = review_spec["reason"]
        review_status = review_spec.get("status", "requires_manual_review")

        review = {
            "blocking": False,
            "reason": reason,
            "sql_files": response.get("sql_files", []),
            "answer_preview": response.get("final_answer", "")[:500],
        }
        existing_result = tc_results.get(query_key)
        if existing_result is None:
            tc_results[query_key] = {"status": review_status, "manual_review": review}
        else:
            existing_result["manual_review"] = review
        logger.warning(f"  {query_key}: {review_status} (non-blocking): {reason}")


def _answer_contains(answer: str, term: Any) -> bool:
    return str(term).casefold() in answer.casefold()


def _missing_answer_terms(answer: str, terms: list[Any] | tuple[Any, ...] | set[Any]) -> list[str]:
    return [str(term) for term in terms if not _answer_contains(answer, term)]


def _missing_answer_term_groups(
    answer: str,
    term_groups: list[list[Any]] | tuple[tuple[Any, ...], ...],
) -> list[list[str]]:
    return [
        [str(term) for term in term_group]
        for term_group in term_groups
        if not any(_answer_contains(answer, term) for term in term_group)
    ]


def _matches_tc_answer_assertion(answer: str, assertion_spec: dict[str, Any]) -> dict[str, Any]:
    required_terms = assertion_spec.get("required_terms", [])
    required_any_term_groups = assertion_spec.get("required_any_term_groups", [])
    absence_answer_terms = assertion_spec.get("absence_answer_terms", [])
    missing_terms = _missing_answer_terms(answer, required_terms)
    missing_groups = _missing_answer_term_groups(answer, required_any_term_groups)
    has_absence_answer = not absence_answer_terms or any(
        _answer_contains(answer, term) for term in absence_answer_terms
    )
    matched = not missing_terms and not missing_groups and has_absence_answer
    return {
        "matched": matched,
        "missing_terms": missing_terms,
        "missing_any_term_groups": missing_groups,
        "missing_absence_terms": [] if has_absence_answer else [str(term) for term in absence_answer_terms],
    }


def _verify_tc_answer_correctness(
    response_by_key: dict[str, dict[str, Any]],
    report_dir: Path,
) -> dict[str, dict[str, Any]]:
    tc_results: dict[str, dict[str, Any]] = {}
    if not any(key in TC_EXPECTED_ANSWER_ASSERTIONS or key in TC_NON_BLOCKING_REVIEW_CASES for key in response_by_key):
        return tc_results

    logger.info("=" * 60)
    logger.info("TC answer fact checks using precomputed expected SQL results")
    failure_messages: list[str] = []

    for query_key, assertion_spec in TC_EXPECTED_ANSWER_ASSERTIONS.items():
        if query_key not in response_by_key:
            continue

        response = response_by_key[query_key]
        if assertion_spec.get("allow_human_feedback_pass") and response.get("hitl_triggered"):
            tc_results[query_key] = {
                "status": "passed_by_human_feedback",
                "expected_summary": assertion_spec.get("expected_summary"),
                "answer_preview": response.get("final_answer", "")[:500],
            }
            logger.info(f"  {query_key}: ✅ auto human feedback triggered; counted as correct")
            continue

        final_answer = str(response.get("final_answer", ""))
        match_result = _matches_tc_answer_assertion(final_answer, assertion_spec)
        sql_evidence_rule = assertion_spec.get("sql_evidence")
        sql_evidence_match = None
        sql_evidence_errors: list[dict[str, str]] = []
        if sql_evidence_rule:
            generated_result_sets: list[dict[str, Any]] = []
            for sql_path in response.get("sql_files", []):
                sql_file = Path(sql_path)
                if ".context" in sql_file.parts or ".memory" in sql_file.parts:
                    continue
                if not sql_file.exists():
                    sql_evidence_errors.append(
                        {"source": str(sql_file), "statement_index": "0", "error": "file not found"}
                    )
                    continue
                result_sets, errors = _execute_sql_result_sets(
                    Path(_ORIGINAL_SQLITE_PATH),
                    sql_file.read_text(encoding="utf-8"),
                    source=str(sql_file),
                )
                generated_result_sets.extend(result_sets)
                sql_evidence_errors.extend(errors)
            sql_evidence_match = _matches_sql_evidence(generated_result_sets, sql_evidence_rule)

        blocking = assertion_spec.get("blocking", True)
        matched = bool(match_result["matched"]) and (
            not sql_evidence_rule or (not sql_evidence_errors and sql_evidence_match is not None)
        )
        status = "passed_by_answer_assertion" if matched else "failed"
        if not blocking:
            status = "passed_with_non_blocking_answer_review" if matched else "non_blocking_answer_assertion_failed"

        tc_results[query_key] = {
            "status": status,
            "blocking": blocking,
            "expected_summary": assertion_spec.get("expected_summary"),
            "missing_terms": match_result["missing_terms"],
            "missing_any_term_groups": match_result["missing_any_term_groups"],
            "missing_absence_terms": match_result["missing_absence_terms"],
            "sql_evidence": sql_evidence_match,
            "sql_evidence_errors": sql_evidence_errors,
            "answer_preview": final_answer[:500],
        }

        if matched:
            logger.info(f"  {query_key}: ✅ answer contains expected facts")
            continue

        message = (
            f"{query_key} answer fact assertion failed. Expected: "
            f"{assertion_spec.get('expected_summary')}\n"
            f"Missing terms: {match_result['missing_terms'] or 'NONE'}\n"
            f"Missing any-term groups: {match_result['missing_any_term_groups'] or 'NONE'}\n"
            f"Missing absence terms: {match_result['missing_absence_terms'] or 'NONE'}\n"
            f"SQL evidence: {sql_evidence_match or 'NONE'}\n"
            f"SQL evidence errors: {sql_evidence_errors or 'NONE'}\n"
            f"Final answer preview:\n{final_answer[:1000]}"
        )
        if blocking:
            failure_messages.append(message)
            logger.error(f"  {query_key}: ❌ answer is missing expected facts")
        else:
            logger.warning(f"  {query_key}: {status} (non-blocking): {message}")

    _record_non_blocking_tc_reviews(response_by_key, tc_results)
    tc_report_path = report_dir / "tc_answer_functional_results_v3.json"
    tc_report_path.write_text(json.dumps(tc_results, ensure_ascii=False, indent=2), encoding="utf-8")
    logger.info(f"TC answer results report: {tc_report_path}")
    logger.info("=" * 60)
    if failure_messages:
        raise AssertionError(
            f"{len(failure_messages)} TC answer fact assertion(s) failed. "
            f"Full report: {tc_report_path}\n\n" + "\n\n".join(failure_messages)
        )
    return tc_results


def _verify_tc_sql_correctness(
    response_by_key: dict[str, dict[str, Any]],
    report_dir: Path,
) -> dict[str, dict[str, Any]]:
    tc_results: dict[str, dict[str, Any]] = {}
    if not any(key in TC_EXPECTED_SQL_ASSERTIONS or key in TC_NON_BLOCKING_REVIEW_CASES for key in response_by_key):
        return tc_results

    expected_db_path = Path(_ORIGINAL_SQLITE_PATH)
    logger.info("=" * 60)
    logger.info(f"TC SQL result-set checks using expected DB: {expected_db_path}")
    failure_messages: list[str] = []

    for query_key, assertion_spec in TC_EXPECTED_SQL_ASSERTIONS.items():
        if query_key not in response_by_key:
            continue

        response = response_by_key[query_key]
        if assertion_spec.get("allow_human_feedback_pass") and response.get("hitl_triggered"):
            tc_results[query_key] = {
                "status": "passed_by_human_feedback",
                "sql_files": response.get("sql_files", []),
            }
            logger.info(f"  {query_key}: ✅ auto human feedback triggered; counted as correct")
            continue

        unqueryable_rule = assertion_spec.get("allow_unqueryable_answer")
        if unqueryable_rule:
            matched = _matches_unqueryable_answer(response, unqueryable_rule)
            tc_results[query_key] = {
                "status": "passed_by_unqueryable_answer" if matched else "failed",
                "sql_files": response.get("sql_files", []),
                "answer_preview": response.get("final_answer", "")[:500],
                "unqueryable_rule": unqueryable_rule,
            }
            if matched:
                logger.info(f"  {query_key}: ✅ schema-boundary answer correctly reports unavailable fields")
                continue
            failure_messages.append(
                f"{query_key} should report the requested fields as unavailable without generating business SQL. "
                f"SQL files: {response.get('sql_files', []) or 'NONE'}\n"
                f"Final answer preview:\n{response.get('final_answer', '')[:1000]}"
            )
            logger.error(f"  {query_key}: ❌ schema-boundary answer assertion failed")
            continue

        absence_rule = assertion_spec.get("absence_assertion")
        if absence_rule:
            sql_files = [
                Path(path)
                for path in response.get("sql_files", [])
                if ".context" not in Path(path).parts and ".memory" not in Path(path).parts
            ]
            generated_result_sets: list[dict[str, Any]] = []
            generated_errors: list[dict[str, str]] = []
            for sql_file in sql_files:
                if not sql_file.exists():
                    generated_errors.append(
                        {"source": str(sql_file), "statement_index": "0", "error": "file not found"}
                    )
                    continue
                result_sets, errors = _execute_sql_result_sets(
                    expected_db_path,
                    sql_file.read_text(encoding="utf-8"),
                    source=str(sql_file),
                )
                generated_result_sets.extend(result_sets)
                generated_errors.extend(errors)

            if absence_rule["kind"] == "schema_field_absent":
                oracle_absent = _schema_fields_are_absent(expected_db_path, absence_rule)
                matched = not generated_errors and oracle_absent and _answer_reports_absence(response, absence_rule)
            else:
                oracle_result_sets, oracle_errors = _execute_sql_result_sets(
                    expected_db_path,
                    absence_rule["oracle_sql"],
                    source=f"{query_key}:absence_oracle",
                )
                oracle_absent = bool(oracle_result_sets) and all(
                    result["row_count"] == 0 for result in oracle_result_sets
                )
                matched = (
                    not generated_errors
                    and not oracle_errors
                    and oracle_absent
                    and _matches_absence_assertion(
                        response,
                        generated_result_sets,
                        absence_rule,
                    )
                )
            tc_results[query_key] = {
                "status": "passed_by_absence_assertion" if matched else "failed",
                "sql_files": [str(path) for path in sql_files],
                "generated_errors": generated_errors,
                "generated_result_sets": [
                    {
                        "source": result["source"],
                        "statement_index": result["statement_index"],
                        "row_count": result["row_count"],
                        "preview_rows": result["preview_rows"],
                        "sql": result["sql"],
                    }
                    for result in generated_result_sets
                ],
                "answer_preview": response.get("final_answer", "")[:500],
                "absence_rule": absence_rule,
            }
            if matched:
                logger.info(f"  {query_key}: ✅ absence assertion passed ({absence_rule['kind']})")
                continue
            failure_messages.append(
                f"{query_key} absence assertion failed ({absence_rule['kind']}). "
                f"Generated errors: {generated_errors or 'NONE'}\n"
                f"Final answer preview:\n{response.get('final_answer', '')[:1000]}"
            )
            logger.error(f"  {query_key}: ❌ absence assertion failed")
            continue

        expected_sql_values = assertion_spec.get("expected_sqls") or [assertion_spec["expected_sql"]]
        expected_result_sets: list[dict[str, Any]] = []
        expected_errors: list[dict[str, str]] = []
        for idx, expected_sql in enumerate(expected_sql_values, 1):
            result_sets, errors = _execute_sql_result_sets(
                expected_db_path,
                expected_sql,
                source=f"{query_key}:expected_sql:{idx}",
            )
            expected_result_sets.extend(result_sets)
            expected_errors.extend(errors)

        sql_files = [
            Path(path)
            for path in response.get("sql_files", [])
            if ".context" not in Path(path).parts and ".memory" not in Path(path).parts
        ]
        generated_result_sets: list[dict[str, Any]] = []
        generated_errors: list[dict[str, str]] = []
        for sql_file in sql_files:
            if not sql_file.exists():
                generated_errors.append({"source": str(sql_file), "statement_index": "0", "error": "file not found"})
                continue
            result_sets, errors = _execute_sql_result_sets(
                expected_db_path,
                sql_file.read_text(encoding="utf-8"),
                source=str(sql_file),
            )
            generated_result_sets.extend(result_sets)
            generated_errors.extend(errors)
        generated_result_sets.extend(_combined_generated_result_sets(generated_result_sets))

        matched = _match_tc_result_sets(
            expected_result_sets,
            generated_result_sets,
            assertion_spec,
        )

        tc_results[query_key] = {
            "status": "passed" if matched else "failed",
            "matched": matched,
            "semantic_mismatch_reason": assertion_spec.get("semantic_mismatch_reason"),
            "sql_files": [str(path) for path in sql_files],
            "expected_result_sets": [
                {
                    "source": result["source"],
                    "row_count": result["row_count"],
                    "preview_rows": result["preview_rows"],
                    "sql": result["sql"],
                }
                for result in expected_result_sets
            ],
            "generated_result_sets": [
                {
                    "source": result["source"],
                    "statement_index": result["statement_index"],
                    "row_count": result["row_count"],
                    "preview_rows": result["preview_rows"],
                    "sql": result["sql"],
                }
                for result in generated_result_sets
            ],
            "expected_errors": expected_errors,
            "generated_errors": generated_errors,
            "answer_preview": response.get("final_answer", "")[:500],
        }

        if matched:
            logger.info(
                f"  {query_key}: ✅ generated SQL matches expected core semantics "
                f"[{matched['match_mode']}] "
                f"({matched['generated']['source']}#{matched['generated']['statement_index']})"
            )
            continue

        first_expected = expected_result_sets[0] if expected_result_sets else None
        first_generated = generated_result_sets[0] if generated_result_sets else None
        failure_messages.append(
            f"{query_key} SQL core semantic mismatch using DB {expected_db_path}.\n"
            f"Generated SQL files: {[str(path) for path in sql_files] or 'NONE'}\n"
            f"Expected errors: {expected_errors or 'NONE'}\n"
            f"Generated errors: {generated_errors or 'NONE'}\n"
            f"Expected first result: "
            f"{ ({'row_count': first_expected['row_count'], 'preview_rows': first_expected['preview_rows'], 'sql': first_expected['sql'][:1000]} if first_expected else 'NONE') }\n"
            f"Generated first result: "
            f"{ ({'row_count': first_generated['row_count'], 'preview_rows': first_generated['preview_rows'], 'sql': first_generated['sql'][:1000]} if first_generated else 'NONE') }\n"
            f"Final answer preview:\n{response.get('final_answer', '')[:1000]}"
        )
        logger.error(f"  {query_key}: ❌ generated SQL does not match expected core semantics")

    _record_non_blocking_tc_reviews(response_by_key, tc_results)
    tc_report_path = report_dir / "tc_sql_functional_results_v3.json"
    tc_report_path.write_text(json.dumps(tc_results, ensure_ascii=False, indent=2), encoding="utf-8")
    logger.info(f"TC SQL results report: {tc_report_path}")
    logger.info("=" * 60)
    if failure_messages:
        raise AssertionError(
            f"{len(failure_messages)} TC SQL core-semantic assertion(s) failed. "
            f"Full report: {tc_report_path}\n\n" + "\n\n".join(failure_messages)
        )
    return tc_results


def verify_functional_correctness(
    per_query_responses: list[dict[str, Any]],
    workspace_dir: Path,
    report_dir: Path,
) -> tuple[dict[str, dict[str, Any]], int | None]:
    # ------------------------------------------------------------------
    # Per-query functional correctness assertions
    # ------------------------------------------------------------------
    # These checks verify that the agent produced the CORRECT answer for
    # each user question — not just that it called the LLM. They catch
    # functional regressions that pure cache-hit-rate metrics miss, e.g.
    # NL2SQL generating SQL that confuses the antibody NAME ("BD55-1111")
    # with its numeric id column (11397) and so failing to create the
    # experiment at all (the qwen-plus run on 2026-06-30 17:11 hit exactly
    # this bug: Q1 silently no-op'd, Q7 then had no experiment to report).
    #
    # Expected values are DB-verified (see EXPECTED_* constants above) and
    # cross-checked against the known-good deepseek reference run
    # cache_test_user_v3_20260630_163422_9a55, which created experiment
    # 902036 with the expected inhibitor/pseudovirus/cell sample ids.
    #
    # Assertions are SKIPPED (with a logger.warning) when their target
    # query wasn't run (e.g. --skip_slow drops Q1; --quick drops Q1-Q3
    # and Q7). This keeps the cache-smoke modes usable while still
    # enforcing correctness on the full 7-query replay.
    logger.info("=" * 60)
    logger.info("TC1 Functional correctness checks:")

    # Build query_key → response dict for fast lookup. per_query_responses
    # preserves execution order which equals QUERY_SEQUENCES order (minus
    # any skipped keys).
    response_by_key: dict[str, dict[str, Any]] = {r["query_key"]: r for r in per_query_responses}

    db_path = workspace_dir / "bio_lab.sqlite"
    today_str = datetime.now().strftime("%Y-%m-%d")
    functional_results: dict[str, dict[str, Any]] = {}

    tc_answer_results = _verify_tc_answer_correctness(response_by_key, report_dir)
    functional_results.update(tc_answer_results)

    # ---- Q1: create_experiment -----------------------------------------
    # The agent MUST have INSERTed a new neutralization_experiments row
    # with the expected inhibitor/pseudovirus/cell sample ids, status=NEW,
    # and start_date=today. The new experiment id (auto-generated, e.g.
    # 902036) is captured here and reused by the Q3 / Q7 assertions.
    created_experiment_id: int | None = None
    if "create_experiment" in response_by_key:
        created_experiment_id = _find_created_experiment_id(db_path, today_str)
        q1_answer = response_by_key["create_experiment"].get("final_answer", "")
        functional_results["create_experiment"] = {
            "created_experiment_id": created_experiment_id,
            "answer_preview": q1_answer[:300],
        }
        assert created_experiment_id is not None, (
            f"Q1 (create_experiment) FAILED: no new neutralization_experiments "
            f"row found in {db_path} with inhibitor_sample_id="
            f"{EXPECTED_BD55_1111_ANTIBODY_SAMPLE_ID}, pseudovirus_sample_id="
            f"{EXPECTED_XBB15_PSEUDOVIRUS_SAMPLE_ID}, cell_sample_id="
            f"{EXPECTED_HUH7_CELL_SAMPLE_ID}, status="
            f"{EXPECTED_NEW_EXPERIMENT_STATUS!r}, start_date={today_str!r}. "
            f"This means the agent did NOT actually create the experiment — "
            f"most likely NL2SQL generated a wrong lookup SQL (e.g. confused "
            f"the antibody NAME 'BD55-1111' with the numeric id column) and "
            f"the create workflow aborted before INSERT. Final answer was:\n"
            f"{q1_answer[:1000]}"
        )
        # The agent's reply should mention the new experiment id.
        assert str(created_experiment_id) in q1_answer, (
            f"Q1 (create_experiment): the agent created experiment "
            f"{created_experiment_id} in the DB but its final answer does "
            f"not mention this id. Final answer was:\n{q1_answer[:1000]}"
        )
        logger.info(
            f"  Q1 create_experiment: ✅ experiment {created_experiment_id} "
            f"created (inhibitor={EXPECTED_BD55_1111_ANTIBODY_SAMPLE_ID}, "
            f"pseudovirus={EXPECTED_XBB15_PSEUDOVIRUS_SAMPLE_ID}, "
            f"cell={EXPECTED_HUH7_CELL_SAMPLE_ID}, status="
            f"{EXPECTED_NEW_EXPERIMENT_STATUS!r}, date={today_str})"
        )
    else:
        logger.warning(
            "  Q1 create_experiment: SKIPPED (not in query sequence — "
            "--skip_slow or --quick mode). Q3/Q7 id-consistency checks "
            "will also be skipped."
        )

    # ---- Q2: find_antibody_neutralization ------------------------------
    # The agent MUST report all 5 pseudoviruses that BD-368 neutralizes
    # with IC50 < 0.1 (and fit_success=1). The response text must contain
    # every expected pseudovirus NAME (subset match is NOT enough — a
    # working agent lists all of them).
    if "find_antibody_neutralization" in response_by_key:
        q2_answer = response_by_key["find_antibody_neutralization"].get("final_answer", "")
        missing = [name for name in EXPECTED_BD368_NEUTRALIZED_PSEUDOVIRUSES if name not in q2_answer]
        functional_results["find_antibody_neutralization"] = {
            "missing_pseudoviruses": missing,
            "answer_preview": q2_answer[:300],
        }
        assert not missing, (
            f"Q2 (find_antibody_neutralization) FAILED: the agent's final "
            f"answer is missing {len(missing)} of the "
            f"{len(EXPECTED_BD368_NEUTRALIZED_PSEUDOVIRUSES)} expected "
            f"pseudovirus names (BD-368 neutralizes with IC50<0.1): "
            f"missing={missing}. Expected all of "
            f"{sorted(EXPECTED_BD368_NEUTRALIZED_PSEUDOVIRUSES)}. "
            f"This usually means the NL2SQL joined on the wrong column "
            f"(e.g. antibodies.id='BD-368' instead of proteins.name='BD-368') "
            f"and returned an empty / partial result. Final answer was:\n"
            f"{q2_answer[:1500]}"
        )
        logger.info(
            f"  Q2 find_antibody_neutralization: ✅ all "
            f"{len(EXPECTED_BD368_NEUTRALIZED_PSEUDOVIRUSES)} expected "
            f"pseudoviruses present "
            f"({sorted(EXPECTED_BD368_NEUTRALIZED_PSEUDOVIRUSES)})"
        )
    else:
        logger.info("  Q2 find_antibody_neutralization: SKIPPED (not in query sequence).")

    # ---- Q3: find_recent_experiment ------------------------------------
    # The most recent experiment for XBB.1.5 + BD55-1111 MUST be the one
    # created in Q1. If Q1 was skipped, this assertion is also skipped
    # (no reference id to compare against).
    if "find_recent_experiment" in response_by_key:
        q3_answer = response_by_key["find_recent_experiment"].get("final_answer", "")
        functional_results["find_recent_experiment"] = {
            "expected_experiment_id": created_experiment_id,
            "answer_preview": q3_answer[:300],
        }
        if created_experiment_id is None:
            logger.warning(
                "  Q3 find_recent_experiment: SKIPPED (Q1 was not run, so "
                "no reference experiment_id to assert against)."
            )
        else:
            assert str(created_experiment_id) in q3_answer, (
                f"Q3 (find_recent_experiment) FAILED: the most recent "
                f"XBB.1.5+BD55-1111 experiment is {created_experiment_id} "
                f"(created in Q1), but the agent's final answer does not "
                f"mention this id. This usually means the lookup SQL used "
                f"the wrong column (e.g. pv.name=123 instead of "
                f"pv.name='XBB.1.5') and returned no rows. "
                f"Final answer was:\n{q3_answer[:1500]}"
            )
            logger.info(f"  Q3 find_recent_experiment: ✅ reports experiment {created_experiment_id} (matches Q1)")
    else:
        logger.info("  Q3 find_recent_experiment: SKIPPED (not in query sequence).")

    # ---- Q4: count_cells -----------------------------------------------
    # Literal interpretation: total distinct cell types in the DB = 2
    # (800002 huh-7, 900300 HEK293T-ACE2). Both ids must appear in the
    # answer. The query wording explicitly says "不同类型" so the literal
    # count interpretation is unambiguous.
    if "count_cells" in response_by_key:
        q4_answer = response_by_key["count_cells"].get("final_answer", "")
        missing_ids = [cid for cid in EXPECTED_CELL_IDS if cid not in q4_answer]
        functional_results["count_cells"] = {
            "expected_count": EXPECTED_CELL_COUNT,
            "expected_ids": sorted(EXPECTED_CELL_IDS),
            "missing_ids": missing_ids,
            "answer_preview": q4_answer[:300],
        }
        assert str(EXPECTED_CELL_COUNT) in q4_answer, (
            f"Q4 (count_cells) FAILED: expected {EXPECTED_CELL_COUNT} cells "
            f"in the DB but the agent's final answer does not mention this "
            f"count. Final answer was:\n{q4_answer[:1000]}"
        )
        assert not missing_ids, (
            f"Q4 (count_cells) FAILED: the agent's final answer is missing "
            f"cell id(s) {missing_ids} (expected all of "
            f"{sorted(EXPECTED_CELL_IDS)}). Final answer was:\n{q4_answer[:1000]}"
        )
        logger.info(f"  Q4 count_cells: ✅ {EXPECTED_CELL_COUNT} cells, ids={sorted(EXPECTED_CELL_IDS)}")
    else:
        logger.info("  Q4 count_cells: SKIPPED (not in query sequence).")

    # ---- Q5: count_viruses ---------------------------------------------
    if "count_viruses" in response_by_key:
        q5_answer = response_by_key["count_viruses"].get("final_answer", "")
        missing_ids = [vid for vid in EXPECTED_PSEUDOVIRUS_IDS if vid not in q5_answer]
        functional_results["count_viruses"] = {
            "expected_count": EXPECTED_PSEUDOVIRUS_COUNT,
            "expected_ids": sorted(EXPECTED_PSEUDOVIRUS_IDS),
            "missing_ids": missing_ids,
            "answer_preview": q5_answer[:300],
        }
        assert str(EXPECTED_PSEUDOVIRUS_COUNT) in q5_answer, (
            f"Q5 (count_viruses) FAILED: expected {EXPECTED_PSEUDOVIRUS_COUNT} "
            f"pseudoviruses in the DB but the agent's final answer does not "
            f"mention this count. Final answer was:\n{q5_answer[:1000]}"
        )
        assert not missing_ids, (
            f"Q5 (count_viruses) FAILED: the agent's final answer is missing "
            f"pseudovirus id(s) {missing_ids} (expected all of "
            f"{sorted(EXPECTED_PSEUDOVIRUS_IDS)}). Final answer was:\n{q5_answer[:1000]}"
        )
        logger.info(
            f"  Q5 count_viruses: ✅ {EXPECTED_PSEUDOVIRUS_COUNT} pseudoviruses, ids={sorted(EXPECTED_PSEUDOVIRUS_IDS)}"
        )
    else:
        logger.info("  Q5 count_viruses: SKIPPED (not in query sequence).")

    # ---- Q6: count_antibodies ------------------------------------------
    if "count_antibodies" in response_by_key:
        q6_answer = response_by_key["count_antibodies"].get("final_answer", "")
        missing_ids = [aid for aid in EXPECTED_ANTIBODY_IDS if aid not in q6_answer]
        functional_results["count_antibodies"] = {
            "expected_count": EXPECTED_ANTIBODY_COUNT,
            "expected_ids": sorted(EXPECTED_ANTIBODY_IDS),
            "missing_ids": missing_ids,
            "answer_preview": q6_answer[:300],
        }
        assert str(EXPECTED_ANTIBODY_COUNT) in q6_answer, (
            f"Q6 (count_antibodies) FAILED: expected {EXPECTED_ANTIBODY_COUNT} "
            f"antibodies in the DB but the agent's final answer does not "
            f"mention this count. Final answer was:\n{q6_answer[:1000]}"
        )
        assert not missing_ids, (
            f"Q6 (count_antibodies) FAILED: the agent's final answer is "
            f"missing antibody id(s) {missing_ids} (expected all of "
            f"{sorted(EXPECTED_ANTIBODY_IDS)}). Final answer was:\n{q6_answer[:1000]}"
        )
        logger.info(
            f"  Q6 count_antibodies: ✅ {EXPECTED_ANTIBODY_COUNT} antibodies, ids={sorted(EXPECTED_ANTIBODY_IDS)}"
        )
    else:
        logger.info("  Q6 count_antibodies: SKIPPED (not in query sequence).")

    # ---- Q7: ask_recent_experiment_id ----------------------------------
    # The agent MUST report the experiment id that Q1 created. If Q1 was
    # skipped, this assertion is also skipped.
    if "ask_recent_experiment_id" in response_by_key:
        q7_answer = response_by_key["ask_recent_experiment_id"].get("final_answer", "")
        functional_results["ask_recent_experiment_id"] = {
            "expected_experiment_id": created_experiment_id,
            "answer_preview": q7_answer[:300],
        }
        if created_experiment_id is None:
            logger.warning(
                "  Q7 ask_recent_experiment_id: SKIPPED (Q1 was not run, so "
                "no reference experiment_id to assert against)."
            )
        else:
            assert str(created_experiment_id) in q7_answer, (
                f"Q7 (ask_recent_experiment_id) FAILED: the user asked for "
                f"the id of the experiment just created in Q1 — expected "
                f"{created_experiment_id}, but the agent's final answer "
                f"does not mention this id. This usually means Q1 silently "
                f"failed to create the experiment (the agent then answers "
                f"'no experiment was created'). Final answer was:\n"
                f"{q7_answer[:1500]}"
            )
            logger.info(f"  Q7 ask_recent_experiment_id: ✅ reports experiment {created_experiment_id} (matches Q1)")
    else:
        logger.info("  Q7 ask_recent_experiment_id: SKIPPED (not in query sequence).")

    # Persist the functional results alongside the cache stats so a failure
    # can be diagnosed offline from the .memory dir.
    functional_report_path = report_dir / "functional_results_v3.json"
    functional_report_path.write_text(
        json.dumps(functional_results, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    logger.info(f"Functional results report: {functional_report_path}")
    logger.info("=" * 60)

    logger.info("=" * 60)
    return functional_results, created_experiment_id
